global using TweetBook.Data;
global using Swashbuckle.AspNetCore.Swagger;
global using System.Reflection;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.OpenApi.Models;
global using System.Linq;
global using System.Net.Mime;
global using static System.Console;